import {
  Dashboard as DashboardIcon,
  LocalShipping as TruckIcon,
  Send as SendIcon,
  Add as PlusIcon,
  Edit as EditIcon,
  People as UsersIcon,
  Description as FileIcon,
  AttachMoney as AttachMoneyIcon,
  Payment as PaymentIcon,
  Business as BusinessIcon,
  Group as GroupIcon,
  AccountBalanceWallet as AccountBalanceWalletIcon,
  MonetizationOn as SalesIcon,
  ReceiptLong as InvoiceIcon,
  RequestQuote as EstimatesIcon,
  Gavel as TaxIcon, // Tax substitute (closest in MUI)
  ProductionQuantityLimits as ProductIcon,
  Store as ShopIcon,
  Receipt as BillIcon, // 👈 Bill icon
  Handshake as VendorIcon, // 👈 Available in MUI v5+
  AccountTree as ChartAccountsIcon,
  MenuBook as JournalEntryIcon,
  PriceChange as PriceChangeIcon,
  Visibility as VisibilityIcon,
  Report as ReportIcon,
  TrendingUp as TrendingUpIcon,
  TrendingDown as TrendingDownIcon,
  AccountBalance as BalanceSheetIcon,
  DriveEta as DriveEtaIcon,
  Delete as DeleteIcon,
  FileUpload as FileUploadIcon,
  FileDownload as FileDownloadIcon,
  PictureAsPdf as PictureAsPdfIcon,
  ArrowForward as ArrowForwardIcon,
  LocalShipping as LocalShippingIcon,
  CreditCard as CreditCardIcon,
  ReceiptLong as ReceiptLongIcon,
  RemoveRedEye as RemoveRedEyeIcon,
  FiberManualRecord as FiberManualRecordIcon,
  ChatBubbleOutline as Communication ,EmojiPeople as Behavior ,Payments as Payment ,BusinessCenter as BusinessStability ,ReportGmailerrorred as ReportScore,
  Cancel as CancelIcon,
  Print as PrintIcon,
  CheckCircle as CheckCircleIcon,
  Transform  as ConvertIcon,
  Settings ,
  Email,
  MarkEmailRead,
  SettingsSuggest,
  Close as CloseIcon
} from "@mui/icons-material";

export type iconType = "dashboard" |"drivers" | "truck" | "OutlineSend" | "plus" | "edit" | "users" | "priceChange" | "visibility" | "customers" | "carriers" | "file" | "company" | "AttachMoneyIcon" | "amazonPay" | "sales" | "accountBalanceWallet" | "invoices" | "estimates" | "tax" | "product" | "purchase" | "vendors" | "bills" | "chartAccounts" | "journalEntry" | "profitAndLoss" | "balanceSheet" | "reports" | "delete" | "fileUpload" | "fileDownload" | "pictureAsPdf" | "arrowForward" | "localShipping" | "creditCard" | "receiptLong" | "GoDotFill" | "communication" | "behavior" | "payment" | "businessStability" | "reportScore" | "cancel" | "fileExport" | "fileImport" | "RemoveRedEye" | "Print" | "checkCircle" | "convert" | "settings" | "email" | "markEmailRead" | "settingsSuggest" | "CloseIcon"
export const getIcon = (iconName?: iconType,props={}): React.ReactElement | null => {
  if (!iconName) return null;

  const iconMap: Record<iconType, React.ReactElement> = {
    dashboard: <DashboardIcon {...props} />,
    truck: <TruckIcon {...props} />,
    drivers:<DriveEtaIcon {...props} />,
    OutlineSend: <SendIcon {...props} />,
    plus: <PlusIcon {...props} />,
    edit: <EditIcon {...props} />,
    users: <UsersIcon {...props} />,
    priceChange: <PriceChangeIcon {...props} />,
    visibility: <VisibilityIcon {...props} />,
    customers: <GroupIcon {...props} />,
    carriers: <TruckIcon {...props} />,
    file: <FileIcon {...props} />,
    company: <BusinessIcon {...props} />,
    AttachMoneyIcon: <AttachMoneyIcon {...props} />,
    amazonPay: <PaymentIcon {...props} />,
    sales: <SalesIcon {...props} />,
    accountBalanceWallet: <AccountBalanceWalletIcon {...props} />,
    invoices: <InvoiceIcon {...props} />,
    estimates: <EstimatesIcon {...props} />,
    tax: <TaxIcon {...props} />,
    product: <ProductIcon {...props} />,
    purchase: <ShopIcon {...props} />,
    vendors: <VendorIcon {...props} />, // ✅ replaced FaHandshake with MUI Handshake
    bills: <BillIcon {...props} />,
    chartAccounts: <ChartAccountsIcon {...props} />,
    journalEntry: <JournalEntryIcon {...props} />,
    profitAndLoss:<>
     <TrendingUpIcon {...props} />
     <TrendingDownIcon {...props} />
    </>,
    balanceSheet: <BalanceSheetIcon {...props} />,
    reports: <ReportIcon {...props} />,
    delete:<DeleteIcon {...props} />,
    fileUpload:<FileUploadIcon {...props} />,
    fileDownload:<FileDownloadIcon {...props} />,
    pictureAsPdf:<PictureAsPdfIcon {...props} />,
    arrowForward:<ArrowForwardIcon {...props} />,
    localShipping:<LocalShippingIcon {...props} />,
    creditCard:<CreditCardIcon {...props} />,
    receiptLong:<ReceiptLongIcon {...props} />,
    GoDotFill:<FiberManualRecordIcon {...props} />,
    communication:<Communication {...props} />,
    behavior:<Behavior {...props} />,
    payment:<Payment {...props} />,
    businessStability:<BusinessStability {...props} />,
    reportScore:<ReportScore {...props} />,
    cancel:<CancelIcon  {...props} />,
    fileExport:<FileDownloadIcon {...props} />,
    fileImport:<FileUploadIcon {...props} />,
    RemoveRedEye:<RemoveRedEyeIcon {...props} />,
    Print:<PrintIcon {...props} />,
    checkCircle:<CheckCircleIcon  {...props} />,
    convert:<ConvertIcon {...props} />,
    settings:<Settings {...props} />,
    email:<Email {...props} />,
    markEmailRead:<MarkEmailRead {...props} />,
    settingsSuggest:<SettingsSuggest {...props} />,
    CloseIcon:<CloseIcon {...props} />
  };

  return iconMap[iconName] || null;
};
